GET http://localhost:3001/logs/errorlogs
Content-Type: application/json
Authorization: eyJraWQiOiJBQUtcL2hyeWxYaGlUTEdrUjNua2htVHZkZFZcLzlSSU1kaWx3ZFhTN1VWTlU9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJmODk3ODEzMi1kZTg0LTRjMmEtYjY5My03NDZkZWRiMjhhNzgiLCJldmVudF9pZCI6ImIxYWFmNjM0LWQzNDYtNDg1Mi05NWU4LWRlOTMxMzI5ZjA5MiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1OTUwOTI4MzcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb21cL2FwLXNvdXRoLTFfcjlmSHRvcm9IIiwiZXhwIjoxNTk1MDk2NDM3LCJpYXQiOjE1OTUwOTI4MzcsImp0aSI6ImYyNmI4Y2Y5LTc2M2YtNDkxNy1iMGEyLTNhYTRjNzRkNmFjMiIsImNsaWVudF9pZCI6Imlsb3M3ZWNocmRvMzVrYXAzZnNycGMxaWwiLCJ1c2VybmFtZSI6InViYWlkIn0.QiYLA_JqgDlPoY1RsGh9uFGfTUpqeLwnGQlCMaD7_6rgNKYw5lkZ7iDwppiR_nawJE_kjZCSNPwxtbSACRhN85VYivQZAxxV9fLslkN_oDMKA3vNnuaX54Er2H-iMo_maXQaBvECVjtun4hi24h7BcBZbcz5zylBmvqRpdpazj3josHXs5hzMQddMJvaKvYzcV-69isIFOIf0gtoZbhuDS0a4fddK08KrWkzDNdB-YxPWBveQBaoFubNBQT0RoAKqiqNs99Kr6drBh63JlJKjXmchg4mB-xqlEkZPkEcCWCfTbLDYKqBmRdw4dorHdYmLxyWorKv_UBxe4uAR0zn8w


# {
#   "name": "ubaid",
#   "password": "abc123"
# }